include $(GOROOT)/src/Make.inc

TARG=gorl

all:$(TARG)

GOFILES=\
	action.go\
	cart_pole.go\
	conf.go\
	environment.go\
	gorlmain.go\
	learner.go\
	mountain_car.go\
	qlearning.go\
	state.go\
	util.go


include $(GOROOT)/src/Make.cmd
